

[theme]
base = "light"  # Use "light" or "dark" for the base theme
primaryColor = "#007bff"  # This is a common blue color (Bootstrap's primary blue)
backgroundColor = "#f5f5f5"
secondaryBackgroundColor = "#ffffff"
textColor = "#000000"
font = "sans serif"
