[theme]
primaryColor = "#002d7a"  # Nearly navy blue for a bold and sophisticated primary color
backgroundColor = "#F0F4F7"  # Very light grayish-blue for a clean and open feel
secondaryBackgroundColor = "#E6EBF1"  # Soft gray for secondary elements
textColor = "#333333"  # Dark gray for readable and gentle contrast
font = "sans-serif"  # Clean and professional sans-serif font
